# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Alexandre Honorat
email: alexandre.honorat@yahoo.fr
description: > # this means to ignore newlines until "baseurl:"
  This is my public site where you'll can find some information
  about me and about projects I'm working on (present or past). 
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://ahonorat.github.io" # the base hostname & protocol for your site
github_username:  ahonorat

# Build settings
markdown: kramdown
